export const regions = [
  { value: 'Zapadno-hercegovačka', label: 'Zapadno-hercegovačka' },
  { value: 'Hercegovačko-neretvanska', label: 'Hercegovačko-neretvanska' },
  { value: 'Unsko-sanska', label: 'Unsko-sanska' },
  { value: 'Posavska', label: 'Posavska' },
  { value: 'Tuzlanska', label: 'Tuzlanska' },
  { value: 'Zeničko-dobojska', label: 'Zeničko-dobojska' },
  { value: 'Bosansko-podrinjska', label: 'Bosansko-podrinjska' },
  { value: 'Srednja-Bosna', label: 'Srednja-Bosna' },
  { value: 'Sarajevo', label: 'Sarajevo' },
  { value: 'Banjalučka', label: 'Banjalučka' },
  { value: 'Dobojsko-bijeljinska', label: 'Dobojsko-bijeljinska' },
  { value: 'Sarajevsko-zvornička', label: 'Sarajevsko-zvornička' },
  { value: 'Trebinjsko-fočanska', label: 'Trebinjsko-fočanska' },
  { value: 'Brčko-distrikt', label: 'Brčko-distrikt' },
  { value: 'Outside of BiH', label: 'Outside of BiH' },
]

export const genders = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
  { value: 'other', label: 'Other' },
]

export const cubics = [
  { value: 1.0, label: '1.0L' },
  { value: 1.1, label: '1.1L' },
  { value: 1.2, label: '1.2L' },
  { value: 1.3, label: '1.3L' },
  { value: 1.4, label: '1.4L' },
  { value: 1.5, label: '1.5L' },
  { value: 1.6, label: '1.6L' },
  { value: 1.7, label: '1.7L' },
  { value: 1.8, label: '1.8L' },
  { value: 1.9, label: '1.9L' },
  { value: 2.0, label: '2.0L' },
  { value: 2.1, label: '2.1L' },
  { value: 2.2, label: '2.2L' },
  { value: 2.3, label: '2.3L' },
  { value: 2.4, label: '2.4L' },
  { value: 2.5, label: '2.5L' },
  { value: 2.6, label: '2.6L' },
  { value: 2.7, label: '2.7L' },
  { value: 2.8, label: '2.8L' },
  { value: 2.9, label: '2.9L' },
  { value: 3.0, label: '3.0L' },
  { value: 3.1, label: '3.1L' },
  { value: 3.2, label: '3.2L' },
  { value: 3.3, label: '3.3L' },
  { value: 3.4, label: '3.4L' },
  { value: 3.5, label: '3.5L' },
  { value: 3.6, label: '3.6L' },
  { value: 3.7, label: '3.7L' },
  { value: 3.8, label: '3.8L' },
  { value: 3.9, label: '3.9L' },
  { value: 4.0, label: '4.0L' },
  { value: 4.1, label: '4.1L' },
  { value: 4.2, label: '4.2L' },
  { value: 4.3, label: '4.3L' },
  { value: 4.4, label: '4.4L' },
  { value: 4.5, label: '4.5L' },
  { value: 4.6, label: '4.6L' },
  { value: 4.7, label: '4.7L' },
  { value: 4.8, label: '4.8L' },
  { value: 4.9, label: '4.9L' },
  { value: 5.0, label: '5.0L' },
];
