export const regions = [
  { value: 'Zapadno-hercegovačka', label: 'Zapadno-hercegovačka' },
  { value: 'Hercegovačko-neretvanska', label: 'Hercegovačko-neretvanska' },
  { value: 'Unsko-sanska', label: 'Unsko-sanska' },
  { value: 'Posavska', label: 'Posavska' },
  { value: 'Tuzlanska', label: 'Tuzlanska' },
  { value: 'Zeničko-dobojska', label: 'Zeničko-dobojska' },
  { value: 'Bosansko-podrinjska', label: 'Bosansko-podrinjska' },
  { value: 'Srednja-Bosna', label: 'Srednja-Bosna' },
  { value: 'Sarajevo', label: 'Sarajevo' },
  { value: 'Banjalučka', label: 'Banjalučka' },
  { value: 'Dobojsko-bijeljinska', label: 'Dobojsko-bijeljinska' },
  { value: 'Sarajevsko-zvornička', label: 'Sarajevsko-zvornička' },
  { value: 'Trebinjsko-fočanska', label: 'Trebinjsko-fočanska' },
  { value: 'Brčko-distrikt', label: 'Brčko-distrikt' },
  { value: 'Outside of BiH', label: 'Outside of BiH' },
]

export const genders = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
  { value: 'other', label: 'Other' },
]

export const cubics = [
  { value: '1.0', label: '1.0' },
  { value: '1.1', label: '1.1' },
  { value: '1.2', label: '1.2' },
  { value: '1.3', label: '1.3' },
  { value: '1.4', label: '1.4' },
  { value: '1.5', label: '1.5' },
  { value: '1.6', label: '1.6' },
  { value: '1.7', label: '1.7' },
  { value: '1.8', label: '1.8' },
  { value: '1.9', label: '1.9' },
  { value: '2.0', label: '2.0' },
  { value: '2.1', label: '2.1' },
  { value: '2.2', label: '2.2' },
  { value: '2.3', label: '2.3' },
  { value: '2.4', label: '2.4' },
  { value: '2.5', label: '2.5' },
  { value: '2.6', label: '2.6' },
  { value: '2.7', label: '2.7' },
  { value: '2.8', label: '2.8' },
  { value: '2.9', label: '2.9' },
  { value: '3.0', label: '3.0' },
  { value: '3.1', label: '3.1' },
  { value: '3.2', label: '3.2' },
  { value: '3.3', label: '3.3' },
  { value: '3.4', label: '3.4' },
  { value: '3.5', label: '3.5' },
  { value: '3.6', label: '3.6' },
  { value: '3.7', label: '3.7' },
  { value: '3.8', label: '3.8' },
  { value: '3.9', label: '3.9' },
  { value: '4.0', label: '4.0' },
  { value: '4.1', label: '4.1' },
  { value: '4.2', label: '4.2' },
  { value: '4.3', label: '4.3' },
  { value: '4.4', label: '4.4' },
  { value: '4.5', label: '4.5' },
  { value: '4.6', label: '4.6' },
  { value: '4.7', label: '4.7' },
  { value: '4.8', label: '4.8' },
  { value: '4.9', label: '4.9' },
  { value: '5.0', label: '5.0' }
];

export const colors = [
  {value: "beige", label: "Beige"},
  {value: "black", label: "Black"},
  {value: "blue", label: "Blue"},
  {value: "brown", label: "Brown"},
  {value: "gold", label: "Gold"},
  {value: "gray", label: "Gray"},
  {value: "green", label: "Green"},
  {value: "orange", label: "Orange"},
  {value: "purple", label: "Purple"},
  {value: "red", label: "Red"},
  {value: "silver", label: "Silver"},
  {value: "white", label: "White"},
  {value: "yellow", label: "Yellow"}
]

export const carTypes = [
  { label: 'Limousine', value: 'Limousine' },
  { label: 'Small Car', value: 'Small Car' },
  { label: 'Caravan', value: 'Caravan' },
  { label: 'Van', value: 'Van' },
  { label: 'SUV', value: 'SUV' },
  { label: 'Convertible', value: 'Convertible' },
  { label: 'Sports Car', value: 'Sports-car' },
  { label: 'Off Road', value: 'Off-Road' },
  { label: 'Caddy', value: 'Caddy' },
  { label: 'Pick-up', value: 'Pickup' },
  { label: 'Oldtimer', value: 'Oldtimer' },
  { label: 'Other', value: 'Other' }
];
